### PR TITLE
Use browsertype enum in SauceOptions.java

### PR DESCRIPTION
**Pull request by jaeheonshim**
Another todo fix mentioned in issue #46

### CODE REVIEW

**Comment by nadvolod** [comment]
@jaeheonshim are you able to see the build logs for Travis? Looks like some tests failed with this PR

**Comment by jaeheonshim** [comment]
I can't see the Travis logs, but the code quality check fail is because of
some code that was already there before I modified.

**Comment by nadvolod** [comment]
@jaeheonshim would you try to pull the latest from master and merge it in with your branch? Then run `mvn test` on your local to see what happens?

**Comment by mmerrell** [comment]
Thanks, @jaeheonshim. I pulled this in as part my more recent commit. Thanks for the contribution!

**Pull request closed without merging**
