### PR TITLE
Factory + Builder FTW

### PR DESCRIPTION
**Pull request by titusfortner**
(this is in Draft because it is mostly just making sure that it is the pattern we want to go with; it's comparing with #237 as baseline)

There will be 3 ways to create Sauce Options.

1. The old way (which this PR deprecates)
The idea was to set each option directly onto the `SauceOptions` instance
```
SauceOptions sauceOptions = new SauceOptions();
        sauceOptions.setBrowserName("chrome);
        sauceOptions.setAvoidProxy(true);
        sauceOptions.setBuild("Sample Build Name");
```
When looking at additional mobile and visual capabilities, we realized there is too much here to set directly and it can be easily overwhelming.
Tests for the old way are implemented in `SauceOptionsDeprecatedTest.java` file

2. The new way
Everything that goes into `sauce:options` gets accessed via `sauce()`
```
SauceOptions sauceOptions = new SauceOptions();
        sauceOptions.setBrowserName("chrome);
        sauceOptions.sauce().setAvoidProxy(true);
        sauceOptions.sauce()setBuild("Sample Build Name");
```
This is a little better, but using this method, there is no way to ensure that only applicable settings are available to the user.
Tests for the new way are implemented in `SauceOptionsTest.java` file

3. The Factory+Builder way!
This makes sure we have a `SauceOptions` instance that only uses valid capabilities for the option selected.

First, use the SauceOptionsFactory to pick the type of test you're running
Then use the build() method to generate the correct options. You need to use sauce() to set sauce specific values like the "new way" above, and you need to use `build()` to generate it all... looks like this:
```
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArgument("--foo");

        SauceOptions sauceOptions = SauceOptionsFactory.chrome(chromeOptions)
                .setPlatformName(SaucePlatform.MAC_CATALINA)
                .sauce()
                        .setBuild("Sample Build Name")
                        .setMaxDuration(300)
                        .build()
                .build();
```
The biggest downside is going to be knowing which factory you want, but theoretically will be easy to tell.
Tests for the Factory+Builder way are implemented in `SauceChromeConfigsTest.java` file

Factory+Builder approach will need to have a lot of code duplication or use the boilerplate, since chaining setters with lombok doesn't work with inheritance. I'm defaulting to more duplication and less boilerplate in this example.

### CODE REVIEW

**Comment by titusfortner** [comment]
Another interesting thing we *could do with this pattern.
Advantage: never need to know anything about "SauceOptions" class
Disadvantage: That's a lot of `build()` methods

```
SauceSession.optionsBuilder()
    .chrome()
        .setPlatformName(SaucePlatform.MAC_CATALINA)
        .sauce()
            .setName("My Test Name")
        .build()
    .build()
.build()
```

**Comment by joshmgrant** [comment]
This just looks plain wrong to me 

```SauceSession.optionsBuilder()
    .chrome()
        .setPlatformName(SaucePlatform.MAC_CATALINA)
        .sauce()
            .setName("My Test Name")
        .build()
    .build()
.build()
```

The "advantage" of being to build a specific Sauce session in a "one-liner" might be countered in both increased complexity of this line and also debugging runtime configuration. It's likely there will be valid but "wrong" configurations and this might be difficult to debug if written this way.

**Comment by titusfortner** [comment]
yeah, I agree, we're getting into the clever/complicated territory with that one.

But what about the `build().build()` of it all in the SauceOptions generation?

**Comment by titusfortner** [comment]
implemented in #246

**Pull request closed without merging**
