### PR TITLE
[java] support Java 8 by removing Java 9 List.of implementation

### PR DESCRIPTION
**Pull request by titusfortner**
So, it looks like when I refactored at one point I removed most of the functionality that required Java 9, so this should "just work."

### CODE REVIEW

**Comment by nadvolod** [comment]
@titusfortner that was fantastically easy!! Should we add one Travis pipeline that runs against JDK 8 to make sure stuff works?

**Review by nadvolod — COMMENTED** [review]
@titusfortner that was fantastically easy!! Should we add one Travis pipeline that runs against JDK 8 to make sure stuff works?

**Comment by titusfortner** [comment]
Sure? I'll see if I can update Travis.

I remember what code I removed. I was using reflection to get all the options class properties dynamically, but then decided I should be explicit and list the ones I needed and just iterate over them.

**Review by nadvolod — APPROVED** [review]

**Review by mmerrell — APPROVED** [review]
Yeah, this looks good to me. Ship it!

**Pull request merged**
